# Generated by Django 5.0.12 on 2025-05-01 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USSD_CORE', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='transactions',
            name='week_of_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
