# Generated by Django 5.0.12 on 2025-05-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USSD_CORE', '0002_transactions_date_transactions_week_of_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Txn_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
