# Generated by Django 5.0.12 on 2025-06-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USSD_CORE', '0004_ussduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='church_name',
            field=models.CharField(blank=True, default='Murangá Church', max_length=255, null=True),
        ),
    ]
