# Generated by Django 5.0.12 on 2025-06-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USSD_CORE', '0005_transactions_church_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
