# Generated by Django 5.2.4 on 2025-08-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USSD_CORE', '0006_transactions_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=20),
        ),
    ]
