# Generated by Django 5.2.4 on 2025-08-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USSD_CORE', '0007_transactions_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Txn_code',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
