# Generated by Django 5.0.12 on 2025-05-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Txn_code', models.CharField(max_length=20)),
                ('Phone_number', models.CharField(max_length=13)),
                ('Txn_type', models.CharField(max_length=20)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Month', models.CharField(max_length=20)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
