# Generated by Django 5.0.12 on 2025-06-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='church_name',
            field=models.CharField(blank=True, default='Murangá Church', max_length=255, null=True),
        ),
    ]
