# Generated by Django 5.0.12 on 2025-06-14 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Section', '0002_transactions_church_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='transactions',
            name='week_of_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='Txn_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
