# Generated by Django 5.0.12 on 2025-06-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=20)),
                ('trans_id', models.CharField(max_length=20, unique=True)),
                ('trans_time', models.CharField(max_length=20)),
                ('trans_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('business_short_code', models.CharField(max_length=10)),
                ('bill_ref_number', models.CharField(max_length=20)),
                ('invoice_number', models.CharField(blank=True, max_length=20, null=True)),
                ('org_account_balance', models.CharField(max_length=20)),
                ('third_party_trans_id', models.CharField(max_length=20)),
                ('msisdn', models.CharField(max_length=13)),
                ('first_name', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
