"""
Django settings for KAG_USSD project.

Generated by 'django-admin startproject' using Django 5.0.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+tm6qt&07eil&lvoolvt@le5awj$+2vs+%-27c$)*v#7t1bc8q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [ "33f0-217-199-148-234.ngrok-free.app", "https://33f0-217-199-148-234.ngrok-free.app","*",'*', "127.0.0.1",
    "localhost"]

CSRF_TRUSTED_ORIGINS = [
    "https://33f0-217-199-148-234.ngrok-free.app"
]


# Application definition

INSTALLED_APPS = [
    #'Users'
    'accounts',
    'Local_Church',
    'Section',
    'District',
    'Mpesa',
    'USSD_CORE',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.humanize',  # <-- Add this line
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'KAG_USSD.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        "DIRS": [BASE_DIR / "templates"],  # global templates directory
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'KAG_USSD.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db_new.sqlite3',
    },
'secondary': {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': BASE_DIR / 'backup_db.sqlite3',
},
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "show_ui_builder": False,  # Hide UI builder (optional)
    "show_version": False,     # Hide the Jazzmin version at the bottom
    "app_list": {},
    # Copyright on the footer
    "search_model": ["auth.User", "auth.Group"],

    "site_title": "KAG MURANGÁ Portal",
    "site_header": "KAG MURANGÁ Portal",
    "site_brand": "KAG MURANGÁ Portal",
    "welcome_sign": "Welcome to the KAG MURANGÁ Portal Admin",
    "copyright": "KAG MURANGÁ & Powered by Apelles Group Intl",

    # Optional customizations
    "site_logo": "images/kag.png",  # Add your logo if needed
    "login_logo": "images/kag.png",
    "show_sidebar": True,
    "navigation_expanded": True,
    "custom_css": "css/jazzmin_override.css",

}
from decouple import config

MPESA_CONSUMER_KEY = config('MPESA_CONSUMER_KEY')
MPESA_CONSUMER_SECRET = config('MPESA_CONSUMER_SECRET')
MPESA_SHORTCODE = config('MPESA_SHORTCODE')
MPESA_PASSKEY = config('MPESA_PASSKEY')
MPESA_CALLBACK_URL = config('MPESA_CALLBACK_URL')
import os

# Read environment variable
MPESA_ENVIRONMENT = os.getenv("MPESA_ENVIRONMENT", "sandbox")

# Decide which base URL to use
if MPESA_ENVIRONMENT == "production":
    MPESA_BASE_URL = "https://api.safaricom.co.ke"
else:
    MPESA_BASE_URL = "https://sandbox.safaricom.co.ke"

# Then build your endpoints
MPESA_OAUTH_URL = f"{MPESA_BASE_URL}/oauth/v1/generate?grant_type=client_credentials"
MPESA_STK_PUSH_URL = f"{MPESA_BASE_URL}/mpesa/stkpush/v1/processrequest"
MPESA_CALLBACK_URL = "https://audience-psychiatry-developed-install.trycloudflare.com/USSD_CORE/mpesa-callback/"

# # M-Pesa Configuration (REPLACE WITH YOUR ACTUAL VALUES)
# MPESA_CONSUMER_KEY = os.environ.get( "a6iYV9Y6HTtMl6sSSHxiCKAvReK0fzGI19WbuZaDGrONqLwb")
# MPESA_CONSUMER_SECRET = os.environ.get( "DXcNySFTrd6AbCwZAAzu6carx114kiFgV92E6KpzXwhTPu3B7GBcdq8N32bN0zr1")
# MPESA_SHORTCODE = '174379'  # Sandbox shortcode
# MPESA_PASSKEY = "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"  # Sandbox passkey
# MPESA_CALLBACK_URL = "https://audience-psychiatry-developed-install.trycloudflare.com/USSD_CORE/mpesa-callback/"

# For production, you'll need to switch to:
# MPESA_SHORTCODE = 'YOUR_PRODUCTION_SHORTCODE'
# MPESA_PASSKEY = 'YOUR_PRODUCTION_PASSKEY'
# And use production URLs:
# - https://api.safaricom.co.ke/oauth/v1/generate (for token)
# - https://api.safaricom.co.ke/mpesa/stkpush/v1/processrequest (for STK)


STATICFILES_DIRS = [
    BASE_DIR / "static",  # If you're using a global static folder
]

STATIC_ROOT = BASE_DIR / "staticfiles"  # Needed if running collectstatic #python manage.py collectstatic --running during production
CSRF_TRUSTED_ORIGINS = [
    "https://audience-psychiatry-developed-install.trycloudflare.com"
]

#DATABASE_ROUTERS = ['Local_Church.routers.DatabaseRouter']

#AUTH_USER_MODEL = 'Users.CustomUser'

# M-Pesa Credentials
# MPESA_ENVIRONMENT = "sandbox"  # or "production"
# MPESA_CONSUMER_KEY = "your_consumer_key"
# MPESA_CONSUMER_SECRET = "your_consumer_secret"
# # MPESA_SHORTCODE = "400200"  # Your Paybill
# MPESA_PASSKEY = "your_passkey"  # For STK push
# MPESA_INITIATOR_NAME = "testapi"
# MPESA_INITIATOR_PASSWORD = "your_encoded_password"

# URLs
MPESA_VALIDATION_URL = "https://audience-psychiatry-developed-install.trycloudflare.com/mpesa/validation/"
MPESA_CONFIRMATION_URL = "https://audience-psychiatry-developed-install.trycloudflare.com/mpesa/confirmation/"

# settings.py
AFRICASTALKING_USERNAME = "Vic Nainas"
AFRICASTALKING_API_KEY = "atsk_7fedc79b1d0570a9a15701bd97cfacb22d1c589bc57bf081ac9459ab33a49e1902bf44db"

LOGIN_REDIRECT_URL = "/dashboard/"  # Where to redirect after login
LOGOUT_REDIRECT_URL = "/accounts/login/"  # Where to redirect after logout
LOGIN_URL = "/accounts/login/"  # Where to redirect for login

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
# Security settings for session management
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True