# Generated by Django 5.0.12 on 2025-05-06 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('week_of_month', models.PositiveIntegerField(blank=True, null=True)),
                ('Ladies', models.IntegerField(default=0)),
                ('Men', models.IntegerField(default=0)),
                ('Youths', models.IntegerField(default=0)),
                ('Teens', models.IntegerField(default=0)),
                ('Children', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Big_Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('week_of_month', models.PositiveIntegerField(blank=True, null=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cash_Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('week_of_month', models.PositiveIntegerField(blank=True, null=True)),
                ('Tithe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Main_Service_Offering', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Mid_Week_Service_Offering', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Children_Offering', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Youths_Offering', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Teens_Offering', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mission_Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Plot_Buying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='USSD_Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('week_of_month', models.PositiveIntegerField(blank=True, null=True)),
                ('Txn_code', models.CharField(max_length=20)),
                ('Phone_number', models.CharField(max_length=13)),
                ('Txn_type', models.CharField(max_length=20)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Month', models.CharField(max_length=20)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('week_of_month', models.PositiveIntegerField(blank=True, null=True)),
                ('Name', models.CharField(max_length=50)),
                ('Main_Service', models.BooleanField()),
                ('Mid_Week_Service', models.BooleanField()),
                ('Phone_number', models.CharField(max_length=13)),
                ('Area_of_residence', models.CharField(max_length=100)),
                ('Reason_for_visit', models.CharField(blank=True, max_length=100, null=True)),
                ('Fellowship_again', models.BooleanField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('year', models.PositiveIntegerField(default=2025)),
                ('church_name', models.CharField(max_length=100)),
                ('section_name', models.CharField(max_length=100)),
                ('district_name', models.CharField(max_length=100)),
                ('attendance_men', models.PositiveIntegerField(default=0)),
                ('attendance_women', models.PositiveIntegerField(default=0)),
                ('attendance_youth', models.PositiveIntegerField(default=0)),
                ('attendance_children', models.PositiveIntegerField(default=0)),
                ('total_visitors', models.PositiveIntegerField(default=0)),
                ('tithes', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('offerings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('youth_offerings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('children_offerings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('missions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('other_givings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_givings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('month', 'year', 'church_name')},
            },
        ),
    ]
