# Generated by Django 5.0.12 on 2025-05-05 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Local_Church', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Big_Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('week_of_month', models.PositiveIntegerField(blank=True, null=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cash_Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('week_of_month', models.PositiveIntegerField(blank=True, null=True)),
                ('Tithe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Main_Service_Offering', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Mid_Week_Service_Offering', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Children_Offering', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Youths_Offering', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Teens_Offering', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Mission_Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Plot_Buying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(default='May', max_length=20)),
                ('year', models.PositiveIntegerField(default=2025)),
                ('church_name', models.CharField(default='Murangá', max_length=100)),
                ('section_name', models.CharField(default='Murangá', max_length=100)),
                ('district_name', models.CharField(default='Mt. Kenya West', max_length=100)),
                ('attendance_men', models.PositiveIntegerField(default=0)),
                ('attendance_women', models.PositiveIntegerField(default=0)),
                ('attendance_youth', models.PositiveIntegerField(default=0)),
                ('attendance_children', models.PositiveIntegerField(default=0)),
                ('tithes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('offerings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('missions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_givings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_givings', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('signature_local_church', models.CharField(blank=True, max_length=100, null=True)),
                ('signature_section', models.CharField(blank=True, max_length=100, null=True)),
                ('pastor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='USSD_Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('week_of_month', models.PositiveIntegerField(blank=True, null=True)),
                ('Txn_code', models.CharField(max_length=20)),
                ('Phone_number', models.CharField(max_length=13)),
                ('Txn_type', models.CharField(max_length=20)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Month', models.CharField(max_length=20)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('week_of_month', models.PositiveIntegerField(blank=True, null=True)),
                ('Name', models.CharField(max_length=50)),
                ('Main_Service', models.BooleanField()),
                ('Mid_Week_Service', models.BooleanField()),
                ('Phone_number', models.CharField(max_length=13)),
                ('Area_of_residence', models.CharField(max_length=100)),
                ('Reason_for_visit', models.CharField(blank=True, max_length=100, null=True)),
                ('Fellowship_again', models.BooleanField()),
            ],
            options={
                'ordering': ['-date'],
                'permissions': [('can_add_visitors', 'Can add visitors'), ('can_change_visitors', 'Can change visitors'), ('can_delete_visitors', 'Can delete visitors'), ('can_view_visitors', 'Can view visitors')],
            },
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
        migrations.AddField(
            model_name='attendance',
            name='Children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='Ladies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='Men',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='Teens',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendance',
            name='Youths',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
