# Generated by Django 5.0.12 on 2025-05-06 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Local_Church', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='attendance_teens',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
