# Generated by Django 5.0.12 on 2025-05-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Local_Church', '0002_big_day_cash_transactions_mission_offering_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitors',
            options={'ordering': ['-date']},
        ),
    ]
