# Generated by Django 5.0.12 on 2025-05-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Local_Church', '0003_attendance_church_name_attendance_district_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='approved_by',
            field=models.CharField(blank=True, default='Bishop Ben Irungu', editable=False, max_length=100, null=True),
        ),
    ]
