# Generated by Django 5.0.12 on 2025-05-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Local_Church', '0005_alter_report_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='approved_by',
            field=models.CharField(default='Bishop Ben Irungu', editable=False, max_length=100),
        ),
    ]
