# Generated by Django 5.0.12 on 2025-05-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Local_Church', '0006_alter_report_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='approved_by',
            field=models.CharField(choices=[('Bishop Ben Irungu', 'Bishop Ben Irungu')], default='Bishop Ben Irungu', max_length=100, null=True),
        ),
    ]
