# Generated by Django 5.0.12 on 2025-06-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Local_Church', '0007_alter_report_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expense_Name', models.CharField(max_length=100)),
                ('Expense_Amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Expense_approved', models.BooleanField()),
            ],
        ),
    ]
