# Generated by Django 5.0.12 on 2025-06-01 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Local_Church', '0008_expenses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenses',
            old_name='Expense_approved',
            new_name='Expense_Approved',
        ),
        migrations.AddField(
            model_name='expenses',
            name='church_name',
            field=models.CharField(choices=[('Murangá Church', 'Murangá Church')], default='unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='expenses',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='expenses',
            name='district_name',
            field=models.CharField(default='MT. KENYA WEST DISTRICT', max_length=100),
        ),
        migrations.AddField(
            model_name='expenses',
            name='section_name',
            field=models.CharField(default='MURANGÁ SECTION', max_length=100),
        ),
        migrations.AddField(
            model_name='expenses',
            name='week_of_month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
