# Generated by Django 5.0.12 on 2025-06-02 07:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Local_Church', '0009_rename_expense_approved_expenses_expense_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Missions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('District_Mission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('KAGDOM_Contribution', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('Monthly_Support', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Missionary_Name', models.CharField(default='Name', max_length=50)),
                ('Total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('church_name', models.CharField(choices=[('Murangá Church', 'Murangá Church')], default='unknown', max_length=100)),
                ('section_name', models.CharField(default='MURANGÁ SECTION', max_length=100)),
                ('district_name', models.CharField(default='MT. KENYA WEST DISTRICT', max_length=100)),
            ],
        ),
    ]
