# Generated by Django 5.0.12 on 2025-06-02 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Local_Church', '0010_missions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='missions',
            old_name='District_Mission',
            new_name='District_Mission_Contribution',
        ),
    ]
