# Generated by Django 5.0.12 on 2025-06-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Local_Church', '0011_rename_district_mission_missions_district_mission_contribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='big_day',
            name='Big_Day',
            field=models.CharField(choices=[('Men Day', 'Men Day'), ('WWK Day', 'WWK Day'), ('Youths Day', 'Youths Day'), ('Teens Day', 'Teens Day'), ('Childrens Day', 'Childrens Day')], default='unknown', max_length=50),
        ),
    ]
