# Generated by Django 5.0.12 on 2025-06-14 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Local_Church', '0012_big_day_big_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='ussd_transactions',
            name='source',
            field=models.CharField(default='local', max_length=20),
        ),
    ]
