# Generated by Django 5.0.12 on 2025-06-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Local_Church', '0013_ussd_transactions_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ussd_transactions',
            name='church_name',
            field=models.CharField(choices=[('Murangá Church', 'Murangá Church')], max_length=100),
        ),
    ]
