# Generated by Django 5.0.12 on 2025-06-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Local_Church', '0014_alter_ussd_transactions_church_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='attendance_children',
            new_name='attendance_Children',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='attendance_men',
            new_name='attendance_Men',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='attendance_teens',
            new_name='attendance_Teens',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='attendance_women',
            new_name='attendance_Women',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='attendance_youth',
            new_name='attendance_Youth',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='total_visitors',
            new_name='total_Visitors',
        ),
        migrations.RemoveField(
            model_name='report',
            name='children_offerings',
        ),
        migrations.RemoveField(
            model_name='report',
            name='missions',
        ),
        migrations.RemoveField(
            model_name='report',
            name='offerings',
        ),
        migrations.RemoveField(
            model_name='report',
            name='tithes',
        ),
        migrations.RemoveField(
            model_name='report',
            name='youth_offerings',
        ),
        migrations.AlterField(
            model_name='report',
            name='district_name',
            field=models.CharField(choices=[('MT. KENYA WEST DISTRICT', 'Murangá Church')], default='MT. KENYA WEST DISTRICT', max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='other_givings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='section_name',
            field=models.CharField(choices=[('Murangá Church', 'Murangá Church')], default='MURANGÁ SECTION', max_length=100),
        ),
        migrations.AddField(
            model_name='report',
            name='Children_Offerings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='report',
            name='Missions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='report',
            name='Offerings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='report',
            name='Tithes',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='report',
            name='Youth_Offerings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
