# Generated by Django 5.2.4 on 2025-08-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Local_Church', '0015_rename_attendance_children_report_attendance_children_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='big_days_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='report',
            name='big_days_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='expense_breakdown',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='expenses',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='report',
            name='mission_offerings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='report',
            name='mission_support',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='report',
            name='plot_contributions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
